import assert from "node:assert/strict";
import test from "node:test";

test("vue package exposes its public entrypoint", async () => {
  const module = await import("../../src/index.js");

  assert.deepEqual(Object.keys(module).sort(), [
    "BelongsToRelationshipField",
    "BooleanField",
    "DateField",
    "DateTimeField",
    "EmailField",
    "FieldShell",
    "FileField",
    "ImageField",
    "NumberField",
    "RenderField",
    "RenderSchemaNode",
    "RenderSchemaTree",
    "ResourceForm",
    "ResourceTable",
    "SelectField",
    "TextField",
    "TextareaField",
    "VerikitProvider",
    "cn",
    "defaultFieldRegistry",
    "fieldAriaProps",
    "fieldId",
    "firstFieldError",
    "firstFieldErrors",
    "getFieldComponent",
    "getValueAtPath",
    "inferAndValidateResource",
    "inferAndValidateSchemaTree",
    "omitFieldError",
    "pathKey",
    "resolveVerikitFields",
    "resourceQueryKeys",
    "setValueAtPath",
    "submitVerikitActionForm",
    "submitVerikitResourceForm",
    "submitVerikitSchemaTreeActionForm",
    "submitVerikitSchemaTreeForm",
    "useActionResource",
    "useCreateResource",
    "useDeleteResource",
    "useListResource",
    "useResourceFind",
    "useResourceForm",
    "useResourceRelationship",
    "useResourceSchemaTreeForm",
    "useResourceTable",
    "useUpdateResource",
    "useVerikitClient",
    "useVerikitForm",
    "useVerikitSchemaTreeForm",
    "validationIssuesToFieldErrors",
  ]);
  assert.equal(
    module.cn("text-sm", false, ["font-medium"]),
    "text-sm font-medium",
  );
});
